services:
  - type: web
    name: laravel-blog-api
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-blog-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-blog-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-blog-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-blog-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-blog-db
          property: password

databases:
  - name: laravel-blog-db
    ipAllowList: []
